### ISSUE TITLE
RS232 connection

### ISSUE THREAD

**Issue by masternso** [dstrigl/htheatpump#171]
* htheatpump version: current
* Python version: 3.7
* Operating System: raspbian
* heatpump: HP12L-M-BC
### Description

I was just about so setup the hardware connection, when I realized there is a second RS232 connection in my heatpump. Is there a way to tell which one is the correct one?
I was about to test the one labeled "Modem COM", but my Serial Adapter Cable has a male pinout - just like both of the connections I found in my heatpump.
Do I need a female cable or is there another connection hidden from my first view?

**Comment by dstrigl** [comment]
That's new for me, that there are Heliotherm heatpumps with more than one serial interface.
My heatpump has only one, which is labeled as "Modem COM" (male pinout).
What you need is a "Null modem" cable, as described here:
https://en.wikipedia.org/wiki/Null_modem

**Comment by masternso** [comment]
Thank you for the clarification - I will try again, when I got the correct cable.

The second interface is not on the same part as the "Modem COM" Port.
It is another circuit board where it is located. I can take a closer look if you are interested ...

**Comment by dstrigl** [comment]
>It is another circuit board where it is located. I can take a closer look if you are interested ...

That would be great. Can you take a photo?

**Comment by masternso** [comment]
Sure. 
I will try to make a little photo-session this weekend ;)

**Comment by masternso** [comment]
Here are the photos.
The second interface is located near the chip labeled "Stromwandler" ... so I don't think it has something to do with the heatpump itself.
![COM2](https://user-images.githubusercontent.com/55556143/65392427-2bf68880-dd75-11e9-81be-59bb5eac78bf.jpg)
![interfaces](https://user-images.githubusercontent.com/55556143/65392428-2bf68880-dd75-11e9-896f-e22d4fcbb043.jpg)

**Comment by dstrigl** [comment]
I have no idea for what the second interface is, but the one labeled with "Modem COM" is the correct one to communicate with the heat pump.

**Comment by masternso** [comment]
Thank you for the clarification.
I wait for the new cable to arrive and then I will give it another try.
