### ISSUE TITLE
invalid syntax by install

### ISSUE THREAD

**Issue by marbe11** [dstrigl/htheatpump#177]
* htheatpump version: last
* Python version: 3.7
* Operating System: debian

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
Im trying to install htheatpump to raspberry pi, but it ended with syntax error

File setup.py, line 7, in <module> from htheatpump import__version__
File "/home/pi/htheatpump/htheatpump/htheatpump.py", line 85 def NONE() -> Set["VerifyAction"]:
SyntaxError: invalid syntax

### What I Did
install from pi and GitHub.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
like at documentation

**Comment by dstrigl** [comment]
Are you really using Python 3.7?

Please post full output of the installation process.

**Comment by marbe11** [comment]
Hi, thank you, first I installed it on old Jessie, now I started with latest clear OS, and the installation went well :-)
Now I get after login FF,FF,FF response from Heliotherm. Do you know, what it mean?
Thank you

**Comment by dstrigl** [comment]
> Now I get after login FF,FF,FF response from Heliotherm. Do you know, what it mean?

No, sorry. But, are you sure the serial settings (baudrate, stopbits, ...) of the Heliotherm heatpump fits with the used settings in htheatpump?

Please always post the whole output of your failed test (command, output, trace, error message, ...).

Regards,
Daniel.

**Comment by marbe11** [comment]
Hello,
Many thanks for your work at Github, now works my SmartHome even better 😊
It was necessary to set the heating pump, enable modem communication, baud 19200.

Thank you very much. Is possible to send some donation to you and how?
Have a nice day
Martin

**Comment by dstrigl** [comment]
Hi Martin,

> Many thanks for your work at Github, now works my SmartHome even better 😊

thanks! Good to hear that it works now.

> It was necessary to set the heating pump, enable modem communication, baud 19200.

As I thought ... 😊 

> Thank you very much. Is possible to send some donation to you and how?

See the "Wanna support me?" section in the README of the project:
https://github.com/dstrigl/htheatpump/blob/master/README.rst#wanna-support-me

Thanks and regards,
Daniel.

**Comment by marbe11** [comment]
Hi, thank you one more, I sent you a couple of beers 😊
Do you have some other work about Smarthome?
Martin
