### ISSUE TITLE
 login failed

### ISSUE THREAD

**Issue by otto76** [dstrigl/htheatpump#191]
* htheatpump version: HP10E-R-Web
* Python version: 3.7.3
* Operating System: Raspberry (4.19.75)

### Description
Tried to run sample script, but got an error 

``` 
HTHEATPUMP: load parameter definitions from: /usr/local/lib/python3.7/dist-packages/htheatpump-1.2.0-py3.7.egg/htheatpump/htparams.csv
INFO:htheatpump.htheatpump:Serial<id=0x764bb990, open=True>(port='/dev/ttyUSB0', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=5, xonxoff=True, rtscts=False, dsrdtr=False)
DEBUG:htheatpump.htheatpump:send request: [b'\x02\xfd\xd0\xe0\x00\x00\x05~LIN;L']
```
...
```
ERROR:htheatpump.htheatpump:login failed after 3 try/tries
ERROR:__main__:login failed after 3 try/tries
Traceback (most recent call last):
  File "htdatetime.py", line 124, in main
    hp.login()
  File "/usr/local/lib/python3.7/dist-packages/htheatpump-1.2.0-py3.7.egg/htheatpump/htheatpump.py", line 609, in login
    raise IOError("login failed after {:d} try/tries".format(retry))
OSError: login failed after 3 try/tries
DEBUG:htheatpump.htheatpump:send request: [b'\x02\xfd\xd0\xe0\x00\x00\x06~LOUT;\x92']
WARNING:htheatpump.htheatpump:logout failed: data stream broken during reading response header

```

### What I Did

run python3 htdatetime.py --device /dev/ttyUSB0 --baudrate 9600
(from /var/log/message:  usb 1-1.2: ch341-uart converter now attached to ttyUSB0)

Tried both pyup-update-pytest-5.3.0-to-5.3.1 and master branches

**Comment by dstrigl** [comment]
Did you configured your serial connection on the Heliotherm heat pump correctly (e.g. Modem type to "direct", baudrate, ...)?

**Comment by otto76** [comment]
To be honest, now - even do not know what and how it should be done.
I do not recognise any point on heatpump where I would be able to do any configuration regarding modem type or bound rate .

Could it be I am missing some authorisation or even physical device?
Then: 
1) what is needed to get it configured 
2) how to verify its done properly 

many thx

**Comment by dstrigl** [comment]
Yes, you have to login as "Fachmann" (sorry, I only know the German setting names of the Heliotherm heat pump) to change the serial connection settings.

This can be done by entering the code "3333" under the heat pump menu "Benutzerebene".
(But keep in mind, under this login level you can change many different things on your heat pump and also damage it!)
Normally you will be logged out to the default user after some time of inactivity.
Or you can switch manually by entering the code "0000".

After that you will find the item "Verbindungsart" under the point "Modem", which should be changed to "Direkt" ("Modem" ->"Verbindungsart" -> "Direkt").
And under the item "Baud Rate" (also under the point "Modem") the prefered baud rate can be choosen.
This should be - of course - fit with the used baud rate of the htheatpump application.
I am using 115200.

After that connect the heat pump with your Raspberry Pi by an null-modem cable (crosslinked!) and try again one of the sample application from the htheatpump package.

Regards,
Daniel.

**Comment by otto76** [comment]
Thx for answer 

I checked the setup I have, and it shows that pump is searching for modem, but no evidence for bound rate or similar settings there. I captured display for Modem section: 
([photos](https://photos.app.goo.gl/vkw6SGPTozuH316A6))

Could it be my cable is defected (Even raspi recognise it)?
Or maybe some other settings are required 
Or probably the reason is because of current heatpumps software version?

Many thanks
O.

**Comment by dstrigl** [comment]
Ok, here are the settings I using on the heat pump:
[https://photos.app.goo.gl/VDAjcMdJyk9gMDis5](url)

> Could it be my cable is defected (Even raspi recognise it)?
Mmh, hard to recognize by remote ...

> Or maybe some other settings are required
No, as far as I know only the serial settings of the heat pump must fit with the settings used on th RPi.

> Or probably the reason is because of current heatpumps software version?
Should not be the case, there are many differnt useres of the htheatpump library with different controller and versions.

Regards,
Daniel.

**Comment by AloisKlingler** [comment]
otto, maybe you can verify you are using a serial cable with crossed RX-TX - also called null modem cable.
on using a normal serial cable you need a small adapter which crosses for you the RX-TX lines.
