### ISSUE TITLE
Frage zu weiteren Parametern

### ISSUE THREAD

**Issue by FelixPetriconi** [dstrigl/htheatpump#203]
Hallo,

kein Bug, sondern nur eine Frage.

Wir haben ganz neu eine der Heliotherm baugleiche WP von Brötje und ich würde gerne weitere Werte protokollieren:

VD-Mod Sollwert
EQ-A02 Istwert
EQ-A02 Zieltemp
Energiewerte Heizung SPF
Energiewerte Wärme SPF
Energiewerte COP 

Ist da ein "Drankommen" an die Werte?

Ich habe kein Problem mit Lowlevel Programmierung, ich bin selbst E-Techniker  und verdiene meine Brötchen mit SW Entwicklung.

Eine Antwort gerne auch per mail an felix at petriconi punkt net.
Vielen Dank und Grüsse,
Felix

**Comment by dstrigl** [comment]
Hallo Felix,

> Ist da ein "Drankommen" an die Werte?

sollte kein Problem sein, wenn diese Werte als Datenpunkte an der WP ausgeführt sind.

Also, alle Parameter auf der Wärmepumpe werden als SP- oder MP-Datenpunkte abgebildet.
Die `htheatpump` liefert schon eine Liste mit den gängigsten Werten mit, siehe hier:
https://htheatpump.readthedocs.io/en/latest/htparams.html

Allerdings kannst du dir diese Liste nach deinem Belieben hin anpassen bzw. erweitern.
Du musst dazu nur die richtige SP- bzw. MP-Nummer ausfindig machen und in der Liste ergänzen.
Dazu kannst du dir deine eigene (benutzerdefinierte) Liste als CSV-Datei unter `~/.htheatpump/htparams.csv` anlegen, welche dann vor der mitgelieferten geladen wird (siehe auch https://htheatpump.readthedocs.io/en/latest/htpackage.html#htheatpump.htparams.HtParams).

Am besten du machst dir einfach mittels dem Beispiel-Script `htbackup.py` ein Backup aller SP- und MP-Datenpunkte der Wärmepumpe und suchst dir die entsprechenden Parameter raus:
```bash
$ python3 htbackup.py --baudrate 9600 --csv backup.csv
'SP,NR=0' [Language]: VAL='0', MIN='0', MAX='4'
'SP,NR=1' [TBF_BIT]: VAL='0', MIN='0', MAX='1'
'SP,NR=2' [Rueckruferlaubnis]: VAL='1', MIN='0', MAX='1'
...
'MP,NR=0' [Temp. Aussen]: VAL='-7.0', MIN='-20.0', MAX='40.0'
'MP,NR=1' [Temp. Aussen verzoegert]: VAL='-6.9', MIN='-20.0', MAX='40.0'
'MP,NR=2' [Temp. Brauchwasser]: VAL='45.7', MIN='0.0', MAX='70.0'
...
```

Anschließend erstellst du dir eine Kopie der Datei `htparams.csv` unter `~/.htheatpump/htparams.csv` und ergänzt die fehlenden Parameter (als neue Zeile in der CSV-Datei).

Danach sollte es möglich sein die Werte z.B. mittels `htquery.py` abzufragen:
```bash
$ python3 htquery.py --device /dev/ttyUSB1 "Energiewerte Heizung SPF" "Energiewerte Wärme SPF" "Energiewerte COP" ...
```

So, ich hoffe das hilft dir weiter ;-)

LG Daniel.

**Comment by FelixPetriconi** [comment]
Hallo Daniel,

ja, das hilft sehr weiter. Nur einige Werte finde ich in der Liste nicht, zB den COP.

Ich habe im Netz dieses Dokument gefunden: https://www.loxwiki.eu/display/LOX/Heliotherm?preview=/6980444/60557489/Modbus-Doku_DE.pdf. Auf den Seite 8ff gibt es Werte namens Web Regler ID. Sind das dieselben, wie die, in Deiner Doku auftauchen?

Falls ja, könnte ich diese in Deiner Doku ergänzen.

VG, Felix

**Comment by dstrigl** [comment]
Hallo Felix,

meine Liste ist nicht ganz vollständig und es werden auch nicht alle SP/MP-Nummern auf allen Wärmepumpen unterstützt (abhängig von Typ, Firmware-Version, usw.). Meine Liste ist sozusagen eine Grundmenge der Parameter, welche so gut wie auf allen Wärmepumpen zu finden sein sollte. Deshalb auch die Möglichkeit eine eigene, benutzerdefinierte Parameterliste zu erstellen.

Für den COP-Wert hast du recht, der findet sich als MP-Datenpunkt an der Nummer 92, zumindest auf meiner WP:
`'MP,NR=92' [COP]: VAL='0.0', MIN='0.0', MAX='10.0'`

> Falls ja, könnte ich diese in Deiner Doku ergänzen.

Der Doku kannst du den Wert / die Werte gerne per Pull-Request beisteuern, die CSV-Datei würde ich aber vorerst gern so schlank belassen. Besteht ja für jeden die Möglichkeit sich seine eigene zusammenzustellen.

LG Daniel.
