### ISSUE TITLE
Probleme mit dem Raspi Autostart

### ISSUE THREAD

**Issue by jackyteam2302** [dstrigl/htheatpump#208]
Hallo. Das Modul läuft auf meinem Raspi 3 und ich bekomme leider den Autostart nicht hin. In der hthttp.py habe ich die IP Adresse vom Raspberry eingetragen und einen Cron Job via crontab -e angelegt @reboot sudo python3 /home/pi/htheatpump/samples/hthttp.py start

wenn ich manuell starte funktioniert alles wunderbar, nur nach einem reboot will der Server nicht starten und es gibt folgenden Fehler

pi@raspberrypi:~ $ tail /tmp/hthttp-daemon.log
  File "/home/pi/htheatpump/samples/hthttp.py", line 256, in run
    server = HTTPServer((args.ip, args.port), HttpGetHandler)
  File "/usr/local/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address
[2020-01-20 21:37:50,486][INFO    ][htheatpump.htheatpump|logout]: logout successfully

Der Raspi hat eine fixe IP. Ich bin nach der Anleitung hier https://www.loxforum.com/forum/hardware-zubeh%C3%B6r-sensorik/10565-heliotherm-rs232-anbindung  vorgegangen.

Vielen Dank für die tolle Arbeit

Beste Grüße
Bernhard

**Comment by dstrigl** [comment]
Eventuell ist das Netzwerk beim Ausführen des Script noch nicht bereit.

Probier mal eine Delay (z.B. 1min) vor dem Ausführen des Script:
`@reboot sleep 60 && ... `

**Comment by jackyteam2302** [comment]
Vielen Dank. Mit der Startverzögerung startet das Modul nach einem Reboot.
