### ISSUE TITLE
Network connection

### ISSUE THREAD

**Issue by herwigmacho** [dstrigl/htheatpump#332]
Hallo, 

ich habe für meine Heliotherm WP08 eine Klasse in c# geschrieben, die mit der Pumpe übers Netzwerk kommuniziert. 
d.h. die Serielle läuft übers MOXA 311 Modem. 

Diese habe ich auch nach php konvertiert. Nun wäre es an der Zeit, dies auch für Python zu machen !

Ich würde dir diese Klasse überlassen, und dich bitten, das in deine Projekte einfließen zu lassen. Was hältst du davon?

Lg Herwig Macho

**Comment by dstrigl** [comment]
Hallo Herwig, das können wir uns gerne mal ansehen.
Finde ich deine Klasse auf github oder anderswo?
Würd mir gern mal ein Bild über die Funktionalität machen ...

LG Daniel.

**Comment by dstrigl** [comment]
Hallo Herwig,

danke für die Einsicht in deinen Code.

Also, wenn es darum geht mit dem htheatpump über das MOXA 311 Modem auf die Heliotherm WP zuzugreifen, das geht recht einfach mittels dem socat Relay (z.B. unter Ubuntu):
`socat pty,link=$HOME/dev/ttyUSB0,raw,echo=0 tcp:192.168.188.41:4001`

Das erzeugt dir eine "virtuelle" serielle Schnittstelle unter `~/dev/ttyUSB0`, mit der du mittels dem htheatpump Modul zugreifen kannst und dann alles per TCP weiter an die angegebene IP (also dein MOXA Modem) weiterleitet.

Natürlich wäre eine native Unterstützung von TCP Sockets im htheatpump Modul cool, aber da muss ich erst etwas Zeit finden ... ist aber auf der Todo-Liste ;-)

LG Daniel.
