### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by reset12** [dstrigl/htheatpump#440]
Hallo,
ich habe eine Brötje BSW Neo 8 und habe mich über ihr Projekt gefreut.
Leider habe ich ein Verbindungsproblem und komme nicht weiter.
htquery --device /dev/ttyUSB0 "Temp. Aussen" "Stoerung"
2022-11-27 19:07:18,172 WARNING [htheatpump.htheatpump|login]: login try #1 failed: data stream broken during reading response header
2022-11-27 19:07:23,294 WARNING [htheatpump.htheatpump|login]: login try #2 failed: data stream broken during reading response header
2022-11-27 19:07:28,413 WARNING [htheatpump.htheatpump|login]: login try #3 failed: data stream broken during reading response header
2022-11-27 19:07:28,526 ERROR [htheatpump.htheatpump|login]: login failed after 3 try/tries
2022-11-27 19:07:28,533 ERROR [htheatpump.scripts.htquery|main]: login failed after 3 try/tries
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/htheatpump-1.3.2-py3.9.egg/htheatpump/scripts/htquery.py", line 140, in main
    hp.login()
  File "/usr/local/lib/python3.9/dist-packages/htheatpump-1.3.2-py3.9.egg/htheatpump/htheatpump.py", line 504, in login
    raise IOError("login failed after {:d} try/tries".format(retry))
OSError: login failed after 3 try/tries
2022-11-27 19:07:33,574 WARNING [htheatpump.htheatpump|logout]: logout failed: data stream broken during reading response header

Was mache ich falsch ?

Ich habe auch hterm installiert und ähnliche Loginprobleme, wobei mir nicht klar ist wie ich den Server mit dem Port 8777 starten soll.

Über Hilfe wäre ich dankbar, ich will keine 500 Euro für ein Interfacee von Brötje ausgeben, wo ich dann keine Kontrolle darüber habe. Ausserdem verbraucht das sehr viel Strom.

Viele Grüsse
Bruno

**Comment by dstrigl** [comment]
Hallo Bruno,

hast du mal gecheckt, ob die Baudrate usw. übereinstimmen? Wie hier z.B. beschrieben:
https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source

LG Daniel.

**Comment by reset12** [comment]
Hallo Daniel,
Danke für die schnelle Antwort.
Es hat mit 19200 Baud geklappt.
Leider konnte ich die Benutzerebene nicht Wechseln, mit 0000 und 3333 als Code hat es nicht geklappt.

Ohne den Code kann ich wohl den Die WP nicht einschalten, wenn ich PV-Überschuss habe.
Ich habe einen 800 Liter Puffer und wollte den Puffer mit dem PV-Überschuss aufladen, d.h. ich wollte die Heizkurve dann nach oben verlegen um die Energie zu puffern. Da ist sicherlich wengier Geld verplempert als wenn ich für 6,8 Cent einspeise.

Es ist ein Super Projekt, ebenso wie das BSB-LAN Projekt für meine Gasheizung welches ich schon lange in Betrieb habe. Ich habe hier alle wichtigen Betriebswerte in einer Grafik auf meinem Webserver und habe dadurch einfach festgestellt, wo ich noch optimieren kann. Es gibt heute Spülmaschinen mit Internetanschluss die niemand braucht, aber keine Heizung die der Kunde selbst steuern kann. Leider habe ich feststellen müssen, das die notwendige Kompetenz bei den Heizungsbauern oft fehlt. Man muss ja froh sein, wenn mal einer kommt.

Also Super und Danke.

Bruno


On Sun, 27 Nov 2022 23:22:23 -0800
Daniel Strigl ***@***.***> wrote:

> Hallo Bruno,
> 
> hast du mal gecheckt, ob die Baudrate usw. übereinstimmen? Wie hier z.B. beschrieben:
> https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source
> 
> LG Daniel.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/dstrigl/htheatpump/issues/440#issuecomment-1328649534
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
***@***.*** ***@***.***>

**Comment by dstrigl** [comment]
Hallo Bruno,

der Code für die Benutzerebene "Fachmann" ist bei der Brötje vielleicht ein anderer. Hatte leider noch nie eine vor mir ;-)
Das Auslesen/Steuern der WP über die Datenpunkte ist aber unabhängig von der Benutzerebene.
Diese dient nur zum Schutz vor ungewollter Änderungen von verschiedenen Einstellungen direkt an der WP.
Die Parameter der Heizkurve usw. solltest du alle mittels diesem Modul durch Ändern der Werte der entsprechenden Datenpunkte ändern können.

LG Daniel.

**Comment by reset12** [comment]
Hallo Daniel,
ich habe in einem Manual den Code gefunden:

Besitzer         0000
Fachmannebene 1  0012
Fachmannebene 2  0112

Viele Grüsse
Bruno

On Tue, 29 Nov 2022 09:06:40 -0800
Daniel Strigl ***@***.***> wrote:

> Hallo Bruno,
> 
> der Code für die Benutzerebene "Fachmann" ist bei der Brötje vielleicht ein anderer. Hatte leider noch nie eine vor mir ;-)
> Das Auslesen/Steuern der WP über die Datenpunkte ist aber unabhängig von der Benutzerebene.
> Diese dient nur zum Schutz vor ungewollter Änderungen von verschiedenen Einstellungen direkt an der WP.
> Die Parameter der Heizkurve usw. solltest du alle mittels diesem Modul durch Ändern der Werte der entsprechenden Datenpunkte ändern können.
> 
> LG Daniel.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/dstrigl/htheatpump/issues/440#issuecomment-1330983359
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
***@***.*** ***@***.***>

**Comment by reset12** [comment]
Hallo Daniel,
ist es möglich, die Energiewerte auszulesen und den Mischerkreis 1.
Bei mir wurde noch ein Mischer installiert, diese Temperaturen tauchen beim Auslesen nicht auf, ebenso, die Energiewerte z.B. die aktuelle Leistungsaufnahme. Ich benötige die Energiewerte zum späteren Steuern wenn die PV Überschuss hat und ebenfalls für die Abrechnung der Heizkosten. Es wäre blöd, wenn ich noch einen Energiezähler installieren muss. Ich wollte mich auch in die Wärmepumendatenbank eintragen und den aktuellen COP mitteilen.  


Anbei ein paar Bilder meiner Aufzeichnungen und der Anzeigen zur Übersicht auf https://privat.bb-24.net/s/Htn8t4kfK8YyCwB


Viele Grüsse
Bruno



-- 
***@***.*** ***@***.***>

**Comment by dstrigl** [comment]
Hallo Bruno,

> ist es möglich, die Energiewerte auszulesen und den Mischerkreis 1.
Alle Werte welche in der WP als Datenpunkt verfügbar sind lassen sich auch auslesen.
Es kann nur sein, dass die von dir gewünschten Datenpunkte nicht Teil des mitgelieferten Parameter-Definitionsfile sind.
Du kannst die gewünschten Datenpunkte aber ganz einfach, so wie hier beschrieben ergänzen:
https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source
(siehe Abschnitt "Parametersatz & -definitionen")
Einfach mittels dem Hilfsscript `htcomplparams ` alle auf der WP verfügbaren Datenpunkte ermitteln und die zusätzlich gewünschten deinem personlisiertem CSV-File unter `~/.htheatpump/htparams.csv` ergänzen!
Siehe dazu auch: https://htheatpump.readthedocs.io/en/latest/htscripts.html#htcomplparams

> Der Command
> curl -X GET "http://localhost:8777/api/v1/param/" -H "accept: application/json"
> gibt nun die Fehlermeldung aus:
> {"message": "write failed: [Errno 5] Input/output error"}
Schaut für mich nach einem Problem mit der seriellen Schnittstelle aus.
Google mal nach Raspberry Pi und der obigen Fehlermeldung ... da kommt man dann meist weiter.

LG Daniel.

**Comment by reset12** [comment]
Hallo Daniel,
Danke für den Tipp. Ich habe den Bootparameter im Raspberry geändert und hoffe das er stabiler läuft.

Die zusätzlichen Parameter habe ich auch eingebaut.
Einfach ein Super Programm.

Viele grüsse
Bruno



On Wed, 14 Dec 2022 01:10:51 -0800
Daniel Strigl ***@***.***> wrote:

> Hallo Bruno,
> 
> > ist es möglich, die Energiewerte auszulesen und den Mischerkreis 1.
> Alle Werte welche in der WP als Datenpunkt verfügbar sind lassen sich auch auslesen.
> Es kann nur sein, dass die von dir gewünschten Datenpunkte nicht Teil des mitgelieferten Parameter-Definitionsfile sind.
> Du kannst die gewünschten Datenpunkte aber ganz einfach, so wie hier beschrieben ergänzen:
> https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source
> (siehe Abschnitt "Parametersatz & -definitionen")
> Einfach mittels dem Hilfsscript `htcomplparams ` alle auf der WP verfügbaren Datenpunkte ermitteln und die zusätzlich gewünschten deinem personlisiertem CSV-File unter `~/.htheatpump/htparams.csv` ergänzen!
> Siehe dazu auch: https://htheatpump.readthedocs.io/en/latest/htscripts.html#htcomplparams
> 
> > Der Command
> > curl -X GET "http://localhost:8777/api/v1/param/" -H "accept: application/json"
> > gibt nun die Fehlermeldung aus:
> > {"message": "write failed: [Errno 5] Input/output error"}
> Schaut für mich nach einem Problem mit der seriellen Schnittstelle aus.
> Google mal nach Raspberry Pi und der obigen Fehlermeldung ... da kommt man dann meist weiter.
> 
> LG Daniel.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/dstrigl/htheatpump/issues/440#issuecomment-1350687075
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
***@***.*** ***@***.***>

**Comment by dstrigl** [comment]
Hallo @reset12,

schön zu hören, dass es nun läuft. Wünsch dir noch viel Spaß damit!

Dann können wir das Issue jetzt schließen, oder?

LG Daniel.

---

[Wanna support me? - Buy Me A Coffee](https://www.buymeacoffee.com/N362PLZ)

[![image](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/N362PLZ)

**Comment by reset12** [comment]
Ja,gerne.

Viele Grüsse
Bruno


On Wed, 14 Dec 2022 22:49:55 -0800
Daniel Strigl ***@***.***> wrote:

> Hallo @reset12,
> 
> schön zu hören, dass es nun läuft. Wünsch dir noch viel Spaß damit!
> 
> Dann können wir das Issue jetzt schließen, oder?
> 
> LG Daniel.
> 
> ---
> 
> [Wanna support me? - Buy Me A Coffee](https://www.buymeacoffee.com/N362PLZ)
> 
> [![image](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/N362PLZ)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/dstrigl/htheatpump/issues/440#issuecomment-1352630626
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
***@***.*** ***@***.***>
